jwt:
  secret: "CHANGE_THIS_TO_A_LONG_RANDOM_SECRET_KEY_AT_LEAST_32_CHARACTERS"
  access-token-expiration: 7200000
  refresh-token-expiration: 6048000000

  aaspaas:
  websocket:
    allowed-origins:
      - http://localhost:4200
      - http://localhost:8100

app:
  otp:
    expiry-minutes: 60
    development-mode: true

        # development-mode: true  ---production ke liye false hoga



  #     aaspaas:
  # websocket:
  #   allowed-origins:
  #     - http://localhost:4200
  #     - http://localhost:8100